//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firma2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAGRIDETAY
    {
        public int ID { get; set; }
        public Nullable<int> CAGRI { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<System.DateTime> TARİH { get; set; }
        public string SAAT { get; set; }
    
        public virtual CAGRIFIRMA CAGRIFIRMA { get; set; }
    }
}
