//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firma2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPANIES()
        {
            this.CAGRIFIRMA = new HashSet<CAGRIFIRMA>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string Officall { get; set; }
        public string PHONE { get; set; }
        public string MAİL { get; set; }
        public string SECTOR { get; set; }
        public string CITY { get; set; }
        public string DISTRICT { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<bool> Situation { get; set; }
        public string PASSWORD { get; set; }
        public string zxc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAGRIFIRMA> CAGRIFIRMA { get; set; }
    }
}
