//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firma2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string MAİL { get; set; }
        public string PHONE { get; set; }
        public string IMAGE { get; set; }
        public Nullable<int> DEPARTMAN { get; set; }
        public Nullable<bool> situation { get; set; }
        public string aaaaa { get; set; }
    
        public virtual TBLDEPARTMAN TBLDEPARTMAN { get; set; }
    }
}
