//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firma2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESAJLAR
    {
        public int ID { get; set; }
        public string GÖNDEREN { get; set; }
        public string ALICI { get; set; }
        public string KONU { get; set; }
        public string MESAJ { get; set; }
        public Nullable<System.DateTime> TARİH { get; set; }
        public Nullable<bool> DURUM { get; set; }
    }
}
